// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || "https://wssjsbtqasaiebyrmxly.supabase.co")

  .trim()
  .replace(/^["']|["']$/g, "")
  .split('/rest/v1')[0]
  .split('/auth/v1')[0]
  .replace(/\/+$/, "");
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_KjlpEdYpPLH5NleaUO0mqw_hbXbrgq_")
  .trim()
  .replace(/^["']|["']$/g, "");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom lock that avoids navigator.locks (unavailable inside the Lovable preview iframe).
async function noOpLock<T>(_name: string, _acquireTimeout: number, fn: () => Promise<T>): Promise<T> {
  return fn();
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    lock: noOpLock,
  }
});
