// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || "https://wssjsbtqasaiebyrmxly.supabase.co")

  .trim()
  .replace(/^["']|["']$/g, "")
  .split('/rest/v1')[0]
  .split('/auth/v1')[0]
  .replace(/\/+$/, "");
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_KjlpEdYpPLH5NleaUO0mqw_hbXbrgq_")
  .trim()
  .replace(/^["']|["']$/g, "");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
